#!/bin/bash
# On lance simplement les commandes using. 
# Comme Binder a déjà installé le Project.toml dans l'environnement par défaut, 
# Julia va les trouver et les précompiler.
julia -e 'using Plots; using PlutoUI; using Distributions;'
