#!/bin/bash
# On demande à Julia d'utiliser le projet du dossier 'binder' et de précompiler les paquets
julia --project=binder -e 'using Pkg; Pkg.instantiate(); using Plots; using PlutoUI; using Distributions;'
